import Head from 'next/head';

function singleNew() {
  return (
   <>
   <Head>
      <title>Ziyo-zukko</title>
      <meta
         name="description"
         content="Generated by create next app"
      />
      <link rel="icon" href="/logo.svg" />
   </Head>
</>
  )
}

export default singleNew
