import Head from 'next/head';
import NewsSingle from '../../../src/Components/NewsPage/NewsSingle';

function singleNew() {
  return (
   <>
   <Head>
      <title>Ziyo-zukko</title>
      <meta
         name="description"
         content="Generated by create next app"
      />
      <link rel="icon" href="/logo.svg" />
   </Head>
   <NewsSingle />
</>
  )
}

export default singleNew
