import Head from 'next/head';
import GalleryPage from '../../src/Components/GalleryPage/GalleryPage';

function Gallery() {
	return (
		<>
			<Head>
				<title>Ziyo-zukko</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/logo.svg" />
			</Head>
			<GalleryPage />
		</>
	);
}

export default Gallery;
