import Head from 'next/head';
import EmployeeSingle from '../../src/Components/AboutPage/EmployeeSingle';

function ManagementSinglePage() {
	return (
		<>
			<Head>
				<title>Ziyo-zukko</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/logo.svg" />
			</Head>
			<EmployeeSingle />
		</>
	);
}

export default ManagementSinglePage;