import AboutPage from "../src/Components/AboutPage/AboutPage"
import Head from 'next/head';

function About() {
   return (
      <>
         <Head>
				<title>Ziyo-zukko</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.svg" />
			</Head>

         <AboutPage />
      </>
   )
}
export default About 