import Head from 'next/head';

import Layout from "../src/Components/layout/layout";


export default function Home() {
	return (
		<>
			<Head>
				<title>Ziyo-zukko</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				
			</Layout>
		</>
	);

}
