import Head from 'next/head';


import HomePage from '../src/Components/HomePage/HomePage';

export default function Home() {
	return (
		<>
			<Head>
				<title>Ziyo-zukko</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.svg" />
			</Head>
					
			
					{/* <HomePage /> */}
			
		</>
	);

}
