import Head from 'next/head';
import NewsPage from '../src/Components/NewsPage/NewsPage';

function News() {
	return (
		<>
			<Head>
				<title>Ziyo-zukko</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/logo.svg" />
			</Head>
			<NewsPage />
		</>
	);
}

export default News;
